### ISSUE TITLE
Custom Binarization of data

### ISSUE THREAD

**Issue by strickland-ev** [pertzlab/arcos4py#4]
### Description
I am very excited to use your tools on my data, and I have been playing with the Napari plug in with great success on my calcium data. The one issue I am having is that when I start using arcos4py tools, your methods for data binarization don't work great for me, and I would like to use my own scheme to binarize the data. Is it possible to directly pass the ARCOS initiation function with the binarization column premade? Eg. 

### measurement column is Calcium, binarization column is Calcium.bin
ts = ARCOS(df_filter_track, ["x", "y"], 'timepoint','track_id', 'Calcium','Calcium.bin')

I have been following the example from here: 
https://arcos.gitbook.io/home/example-use-cases/detecting-collective-signalling-events-in-epithelial-cells

I am also having difficulty understanding how the binarization methods work. I can input data with long tracks (>50 timeframes) and the same cell ID is given back with only ~7 timepoints and different x and y positions etc. Is there some shuffling of the track_id when tracking collective events?

**Comment by bgraedel** [comment]
Hi @jdstrickland, 

First great that you are enjoying using the packages!

There are two ways you can pass your custom binarization column to arcos. 
1. the ARCOS class has a class attribute "bin_col". You can construct the class as usual. The constructor creates the value for this class attribute by adding a ".bin" suffix to the name of the measurement column. So if your measurement column is "Calcium" and you have a "Calcium.bin" in your data you should be able to skip the binarization method entirely. Alternatively, you could create the arcos object with: 
`ts = ARCOS(df_filter_track, ["x", "y"], 'timepoint','track_id', 'Calcium')` and then
`ts.bin_meas = "your_binary_column"` 
and again skipping the binarization step.

2. The easier option for you however would be to directly use what the "trackCollev" method calls.
```
from arcos4py.tools import detectCollev
ts = detectCollev(args)
events_df = ts.run()
```
this allows you to directly pass in the binarized data to arcos.
here would be the documentation for this: https://bgraedel.github.io/arcos4py/api/#arcos4py.tools.detect_events

It is still very odd that there is some reshuffling with the tracked data. It sounds like a bug on my side. On which package version are you? I did fix some binarization issues with the latest release (0.1.4). 
If you have this version installed and the issue persists could you (if that is ok with you) send me your data as a CSV so I could have a closer look at what might be going wrong?

**Comment by strickland-ev** [comment]
Thanks for the quick reply @bgraedel. 

I just plugged my binarization scheme into the ARCOS algorithm using method 1. It works beautifully, and I am excited to get to more of the downstream analysis as I get this working more. 

The second issue I think was my fault. I was misunderstanding the output of the ARCOS after detectCollev was run. I will let you know if I run into any more issues, but right now things seem to be working really well. 

Thank you for your guidance, I will let you know if I run into any more issues!
